# Numpy

In [1]:
import numpy as np
np.__version__

'1.21.5'

# 1D Array

In [2]:
#create 1d array with the help of list
l=[10,20,30,40,50]
print('type of list : ',type(l))
#converting into array 
a=np.array(l)
print('type of aaray : ',type(a))
a

type of list :  <class 'list'>
type of aaray :  <class 'numpy.ndarray'>


array([10, 20, 30, 40, 50])

In [3]:
#to see the dimension
a.ndim

1

In [4]:
#to see no of rows and cols
a.shape

(5,)

In [5]:
#to see no of rows only
a.shape[0]

5

In [6]:
a.size

5

In [7]:
len(a)

5

In [8]:
#to see the datatype
a.dtype

dtype('int32')

In [9]:
#to see no of bytes taken by each element 
a.itemsize

4

In [10]:
#to see total no of bytes taken by array a
a.itemsize*a.size

20

In [11]:
#to see directly 
a.nbytes

20

In [12]:
#to create an array directly 
x=np.array([10,20.5,30,40,50])
x

array([10. , 20.5, 30. , 40. , 50. ])

In [13]:
x.dtype

dtype('float64')

In [14]:
#to get a particular dtype
x=np.array([10,20.5,30,40,50],int)
x.dtype

dtype('int32')

In [15]:
#to show values in iterative way
x=np.array([10,20,30,40,50])
for i in x:
    print(i)

10
20
30
40
50


In [16]:
#to see values along with indexes
x=np.array([10,20,30,40,50])
for i,v in enumerate(x):
    print(i,' ',v)

0   10
1   20
2   30
3   40
4   50


In [17]:
#to extract data from numpy array
#indexing
x=np.array([10,20,30,40,50])
#to extract 1st elemnent
print('1st elemnent: ',x[0])
#to extract last elemnent
print('Last elemnent: ',x[-1])

1st elemnent:  10
Last elemnent:  50


In [18]:
#multiple indexing , here we can pass the index nos in a list and extract the values 
x=np.array([10,20,30,40,50])
x[[0,2,4]]

array([10, 30, 50])

In [19]:
#slicing
x=np.array([10,20,30,40,50])
#to extract first 2 elements
print('first 2 elements: ',x[:2])
#to extract last 2 elements
print('first 2 elements: ',x[-2:])

first 2 elements:  [10 20]
first 2 elements:  [40 50]


In [20]:
#to access all even nos
x=np.array([10,15,20,25,30,35])
x%2==0 #returns true for even 

array([ True, False,  True, False,  True, False])

In [21]:
#to show with nos 
x=np.array([10,15,20,25,30,35])
x[x%2==0]

array([10, 20, 30])

In [22]:
#odd nos
x=np.array([10,15,20,25,30,35])
x[x%2!=0]

array([15, 25, 35])

In [23]:
#to check path 
import os
os.getcwd()

'C:\\Users\\HP'

In [24]:
#to replace all even nos with 0
x=np.array([10,15,20,25,30,35])
np.where(x%2==0,0,x)

array([ 0, 15,  0, 25,  0, 35])

In [25]:
#to see all arithmatic operations
np.sum(x)

135

In [26]:
x.sum()

135

In [27]:
x.max()

35

In [28]:
x.min()

10

In [29]:
x.mean()

22.5

In [30]:
#second way to create an 1d array
#we use arange() an inbuilt method
b=np.arange(10,50,5)
b

array([10, 15, 20, 25, 30, 35, 40, 45])

# 2D Array

In [31]:
a=np.array([[55,70,92],[42,34,78],[80,62,85]])
print(a.ndim,'dimension')
a

2 dimension


array([[55, 70, 92],
       [42, 34, 78],
       [80, 62, 85]])

In [32]:
#to access data from 2d array
#indexing
#to get data from 2row and 2col
a[2,2] #a[row index,col index]

85

In [33]:
#to access data from 2nd row
a[2,]

array([80, 62, 85])

In [34]:
#slicing
a[1:3,1:3]

array([[34, 78],
       [62, 85]])

In [35]:
#to get last row data
a[-1:]

array([[80, 62, 85]])

In [36]:
#to get last col data
a[: ,-1]

array([92, 78, 85])

In [37]:
#to get even nos
a[a%2==0]

array([70, 92, 42, 34, 78, 80, 62])

In [38]:
#to get sum 
a.sum()

598

In [39]:
a.sum(axis=0)

array([177, 166, 255])

In [40]:
#to merge 2 2d array 
#we use concatenate()
x=np.array([[0,1,2],[3,4,5]])
y=np.array([[6,7,8],[9,10,11]])
z=np.concatenate((x,y),axis=0)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
z.ndim

2

In [42]:
#sorting
#to get in desc order
x=np.array([[0,3,1,2],[4,5,7,6],[8,11,10,9],[12,13,14,15]])
c=np.sort(x,axis=0)[::-1]
c

array([[12, 13, 14, 15],
       [ 8, 11, 10,  9],
       [ 4,  5,  7,  6],
       [ 0,  3,  1,  2]])

In [43]:
#to convert 2d in 1d permanently
c=c.reshape(-1)
c.ndim
print(c)

[12 13 14 15  8 11 10  9  4  5  7  6  0  3  1  2]


In [58]:
c=c.reshape(2,2)
c.ndim
print(c)

[[ 6  8]
 [10 12]]


In [44]:
y=x.reshape(8,2)
y.ndim

2

In [45]:
y

array([[ 0,  3],
       [ 1,  2],
       [ 4,  5],
       [ 7,  6],
       [ 8, 11],
       [10,  9],
       [12, 13],
       [14, 15]])

In [59]:
#arithmatic operations on 2 or more matrix
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [60]:
#addition
c=a+b
print(c)

[[ 6  8]
 [10 12]]


In [61]:
#subtraction
d=a-b
print(d)

[[-4 -4]
 [-4 -4]]


In [62]:
#multiplication
e=a*b
print(e)

[[ 5 12]
 [21 32]]


In [47]:
#zero()
z=np.zeros((2,3))
print(z)
#to update value at 0th row and 1st col
z[0,1]=10
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]
[[ 0. 10.  0.]
 [ 0.  0.  0.]]


In [48]:
#ones()
o=np.ones((2,4))
print(o)
o[1,1]=10
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.  1.  1.  1.]
 [ 1. 10.  1.  1.]]


In [49]:
#identity or eye
i=np.identity((2))
print(i)
e=np.eye((2))
print(e)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [64]:
#empty()
g=np.empty((2,3),int)
print(g)

[[ 6  7  8]
 [ 9 10 11]]


In [51]:
#vstack - stacks arrays in vertical way row wise ,its filo-first in last out
x=np.array([0,3,1,2])
y=np.array([4,5,7,6])
z=np.vstack((x,y))
z

array([[0, 3, 1, 2],
       [4, 5, 7, 6]])

In [52]:
#hstack - stacks arrays in horizontal way col wise ,its fifo-first in first out
x=np.array([0,3,1,2])
y=np.array([4,5,7,6])
z=np.hstack((x,y))
z

array([0, 3, 1, 2, 4, 5, 7, 6])

In [65]:
#broadcasting
x=np.array([[0,1,2],[3,4,5]])
print(x)
y=np.array([6,7,8])
print(y)
print('addition is : ',x+y)

[[0 1 2]
 [3 4 5]]
[6 7 8]
addition is :  [[ 6  8 10]
 [ 9 11 13]]


In [54]:
#transpose or transpose()
x.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [66]:
#append - to add one or more rows in 2d array
x=np.array([[0,1,2],[3,4,5]])
print(x)
y=np.array([[6,7,8],[9,10,11]])
print(y)
z=np.append(x,y,axis=0)
print(z)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
#to add a col in 2d array
x=np.array([[1,2],[3,4]])
y=np.array([[6,7]])
x=np.append(x,y.transpose(),axis=1)
print(x)

[[1 2 6]
 [3 4 7]]
